version: '3'
services:
  molpatch:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input_multiple:/input
      - ./output:/output
    command: 
      -rh
      -rhetm
      -sc
      -pf 0
